# Fabric notebook source

# METADATA ********************

# META {
# META   "kernel_info": {
# META     "name": "synapse_pyspark"
# META   },
# META   "dependencies": {
# META     "lakehouse": {
# META       "default_lakehouse": "22746de3-183e-4327-a844-dceda0b7165c",
# META       "default_lakehouse_name": "Sales_Forecasting",
# META       "default_lakehouse_workspace_id": "991f5e4b-c174-4ff2-992e-feb17d49d25a",
# META       "known_lakehouses": [
# META         {
# META           "id": "22746de3-183e-4327-a844-dceda0b7165c"
# META         }
# META       ]
# META     }
# META   }
# META }

# CELL ********************

import pandas as pd
from pyspark.sql.functions import *
from pyspark.sql.types import StructType, StructField, StringType
from pyspark.sql.window import Window

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

## Parameters to set from the pipeline
Topline = True
driver_status = "Manual_Drivers"    ## options: "No_Drivers", "Manual_Drivers", "Automated_Drivers" 

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

%run Config_Prod

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

config_obj = build_config(
    topline=Topline,
    driver_status=driver_status
)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

recommneded_path = config_obj['manual_recommended_features_path']
final_features_path = config_obj['manual_final_features_path']
drv_grp_cols = config_obj['manual_drv_grp_cols']
act_grp_cols = config_obj['manual_act_grp_cols']


partition_cols = list(dict.fromkeys(drv_grp_cols+act_grp_cols))
if 'series' in partition_cols:
    partition_cols.remove('series')


# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

temp_df = pd.read_excel(recommneded_path)
df = spark.createDataFrame(temp_df)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

all_drivers = spark.read.table(driver_table)


# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

df = df.drop('abs_corr','max_corr')

w_ = Window.partitionBy(*partition_cols)
df = df.withColumn('abs_corr', round(abs(col('Correlation')),4)).withColumn('max_corr', max(col('abs_corr')).over(w_))
df = df.withColumn('final_test_flag', when(col('max_corr')==col('abs_corr'),lit(1)).otherwise(lit(0)))
df = df.withColumn('rec_lag', col('final_test_flag')).drop('final_test_flag')


# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

topline_raw = """
ALU	Food_Processing_Plants
ALU	Cold_Storage_Plants
ALU	Leisure_Hospitality_Buildings
ALU	Stores
ALU	Industrial_production_excluding_Construction_NACE_rv2_05_to_39_Industrial_Production
ALU	Food_beverages_NACE_rv2_10_11_Investment_Real_USD
ALU	Special_purpose_machinery_NACE_rv2_28_3_28_4_28_9_Value_added_output_Real_USD
ALU	International_investment_position_Net_total
ALU	Whole_Economy_Producer_Price_Index
ALU	Manufacturing_NACE_rv2_10_to_33_Gross_output_sales_Real_USD
ALU	General_purpose_machinery_NACE_rv2_28_1_28_2_Investment_Real_USD
ALU	Mechanical_engineering_NACE_rv2_28_Value_added_output_Real_USD
ALU	Real_GVA_in_construction
ALU	Gas_steam_cooling_ice_manufacture_distribution_NACE_rv2_35_2_to_35_3_Value_added_output_Real_USD
ALU	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Value_added_output_Real_USD
ALU	Index_of_industrial_production
AVP_CDU	Gas_steam_cooling_ice_manufacture_distribution_NACE_rv2_35_2_to_35_3_Investment_Real_USD
AVP_CDU	Engineering_metal_goods_NACE_rv2_25_27_28_Gross_output_sales_Real_USD
AVP_CDU	Castings_NACE_rv2_24_5_Investment_Real_USD
AVP_CDU	International_investment_position_Net_total
AVP_CDU	Electricity_gas_air_conditioning_NACE_rv2_35_Investment_Real_USD
AVP_CDU	CO2_emissions
AVP_CDU	Special_purpose_machinery_NACE_rv2_28_3_28_4_28_9_Investment_Real_USD
AVP_CDU	General_purpose_machinery_NACE_rv2_28_1_28_2_Investment_Real_USD
AVP_CDU	Mechanical_engineering_NACE_rv2_28_Value_added_output_Real_USD
AVP_CDU	Real_GVA_in_construction
AVP_CDU	Food_beverages_NACE_rv2_10_11_Investment_Real_USD
AVP_CDU	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Gross_output_sales_Real_USD
AVP_CDU	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Value_added_output_Real_USD
AVP_CDU	Index_of_industrial_production
AVP_CDU	Food_Processing_Plants
AVP_CDU	Cold_Storage_Plants
HEXPV	Whole_Economy_Producer_Price_Index
HEXPV	Engineering_metal_goods_NACE_rv2_25_27_28_Gross_output_sales_Real_USD
HEXPV	General_purpose_machinery_NACE_rv2_28_1_28_2_Gross_output_sales_Real_USD
HEXPV	Manufacturing_NACE_rv2_10_to_33_Gross_output_sales_Real_USD
HEXPV	Mechanical_engineering_NACE_rv2_28_Gross_output_sales_Real_USD
HEXPV	International_investment_position_Net_total
HEXPV	Index_of_industrial_production
HEXPV	Industrial_production_including_construction_excluding_utilities_NACE_rv2_05_to_33_41_to_43_Carbon_Emissions
HEXPV	Castings_NACE_rv2_24_5_Investment_Real_USD
HEXPV	Data_Center
HEXPV	General_purpose_machinery_NACE_rv2_28_1_28_2_Investment_Real_USD
HEXPV	Mechanical_engineering_NACE_rv2_28_Value_added_output_Real_USD
HEXPV	Real_GVA_in_construction
HEXPV	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Gross_output_sales_Real_USD
HEXPV	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Value_added_output_Real_USD
MAERSK_COMPRESSOR	General_purpose_machinery_NACE_rv2_28_1_28_2_Investment_Real_USD
MAERSK_COMPRESSOR	Real_GVA_in_industry
MAERSK_COMPRESSOR	International_investment_position_Net_total
MAERSK_COMPRESSOR	Electricity_installed_capacity
MAERSK_COMPRESSOR	Gas_steam_cooling_ice_manufacture_distribution_NACE_rv2_35_2_to_35_3_Investment_Real_USD
MAERSK_COMPRESSOR	Motor_vehicles_NACE_rv2_29_1_Production_of_commercial_vehicles
MAERSK_COMPRESSOR	Castings_NACE_rv2_24_5_Value_added_output_Real_USD
MAERSK_COMPRESSOR	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Gross_output_sales_Real_USD
MAERSK_COMPRESSOR	Index_of_industrial_production
MAERSK_COMPRESSOR	Accommodation_catering_NACE_rv2_55_56_Investment_Real_USD
MAERSK_COMPRESSOR	Mechanical_engineering_NACE_rv2_28_Value_added_output_Real_USD
MAERSK_COMPRESSOR	Real_GVA_in_construction
MAERSK_COMPRESSOR	Food_beverages_NACE_rv2_10_11_Investment_Real_USD
MAERSK_COMPRESSOR	Gas_steam_cooling_ice_manufacture_distribution_NACE_rv2_35_2_to_35_3_Value_added_output_Real_USD
MAERSK_COMPRESSOR	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Value_added_output_Real_USD
MAERSK_ELECTRONICS	Gas_steam_cooling_ice_manufacture_distribution_NACE_rv2_35_2_to_35_3_Value_added_output_Real_USD
MAERSK_ELECTRONICS	General_purpose_machinery_NACE_rv2_28_1_28_2_Investment_Real_USD
MAERSK_ELECTRONICS	Industrial_production_including_construction_excluding_utilities_NACE_rv2_05_to_33_41_to_43_Carbon_Emissions
MAERSK_ELECTRONICS	Motor_vehicles_NACE_rv2_29_1_Production_of_commercial_vehicles
MAERSK_ELECTRONICS	Whole_Economy_Industrial_Production
MAERSK_ELECTRONICS	Electricity_gas_air_conditioning_NACE_rv2_35_Value_added_output_Real_USD
MAERSK_ELECTRONICS	Transport_equipment_NACE_rv2_29_30_Investment_Real_USD
MAERSK_ELECTRONICS	Engineering_metal_goods_NACE_rv2_25_27_28_Investment_Real_USD
MAERSK_ELECTRONICS	External_trade_Total_trade
MAERSK_ELECTRONICS	Mechanical_engineering_NACE_rv2_28_Value_added_output_Real_USD
MAERSK_ELECTRONICS	Real_GVA_in_construction
MAERSK_ELECTRONICS	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Gross_output_sales_Real_USD
MAERSK_ELECTRONICS	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Value_added_output_Real_USD
MAERSK_ELECTRONICS	Index_of_industrial_production
PISTON	Special_purpose_machinery_NACE_rv2_28_3_28_4_28_9_Value_added_output_Real_USD
PISTON	Mechanical_engineering_NACE_rv2_28_Value_added_output_Real_USD
PISTON	Gas_steam_cooling_ice_manufacture_distribution_NACE_rv2_35_2_to_35_3_Investment_Real_USD
PISTON	CO2_emissions
PISTON	Wood_wood_products_Pulp_paper_Rubber_plastic_Non_metallic_minerals_NACE_rv2_16_to_17_22_to_23_Industrial_and_building_materials_chartbook_consistent_NACE_rv2_16_to_17_22_to_23
PISTON	General_purpose_machinery_NACE_rv2_28_1_28_2_Value_added_output_Real_USD
PISTON	Manufacturing_NACE_rv2_10_to_33_Electricity_demand
PISTON	Industrial_production_excluding_Construction_NACE_rv2_05_to_39_Industrial_Production
PISTON	Engineering_metal_goods_NACE_rv2_25_27_28_Gross_output_sales_Real_USD
PISTON	Gas_steam_cooling_ice_manufacture_distribution_NACE_rv2_35_2_to_35_3_Gross_output_sales_Real_USD
PISTON	General_purpose_machinery_NACE_rv2_28_1_28_2_Investment_Real_USD
PISTON	Real_GVA_in_construction
PISTON	Gas_steam_cooling_ice_manufacture_distribution_NACE_rv2_35_2_to_35_3_Value_added_output_Real_USD
PISTON	Index_of_industrial_production
PISTON	Food_Processing_Plants
PISTON	Cold_Storage_Plants
SCREWS	Food_beverages_tobacco_NACE_rv2_10_to_12_Electricity_demand
SCREWS	Electricity_consumption
SCREWS	Chemicals_NACE_rv2_20_Investment_Real_USD
SCREWS	IT_Programming_consultancy_information_services_NACE_rv2_62_to_63_Investment_Real_USD
SCREWS	Food_beverages_NACE_rv2_10_11_Investment_Real_USD
SCREWS	Manufacturing_NACE_rv2_10_to_33_Investment_Real_USD
SCREWS	Whole_Economy_Price_of_energy_for_industr
SCREWS	General_purpose_machinery_NACE_rv2_28_1_28_2_Investment_Real_USD
SCREWS	Mechanical_engineering_NACE_rv2_28_Value_added_output_Real_USD
SCREWS	Real_GVA_in_construction
SCREWS	Food_Processing_Plants
SCREWS	Cold_Storage_Plants
SCREWS	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Gross_output_sales_Real_USD
SCREWS	Index_of_industrial_production
SCREWS	Data_Center
SCROLLS	Building_stock_by_type_Non_residential_number_of_buildings
SCROLLS	Data_Center
SCROLLS	Food_Processing_Plants
SCROLLS	Cold_Storage_Plants
SCROLLS	Stores
SCROLLS	Leisure_Hospitality_Buildings
SCROLLS	Special_purpose_machinery_NACE_rv2_28_3_28_4_28_9_Investment_Real_USD
SCROLLS	Mechanical_engineering_NACE_rv2_28_Investment_Real_USD
SCROLLS	Accommodation_catering_NACE_rv2_55_56_Investment_Real_USD
SCROLLS	Industrial_production_excluding_Construction_NACE_rv2_05_to_39_Investment_Nominal_USD
SCROLLS	Real_GVA_in_construction
SCROLLS	General_purpose_machinery_NACE_rv2_28_1_28_2_Investment_Real_USD
SCROLLS	Mechanical_engineering_NACE_rv2_28_Value_added_output_Real_USD
SCROLLS	Gas_steam_cooling_ice_manufacture_distribution_NACE_rv2_35_2_to_35_3_Value_added_output_Real_USD
SCROLLS	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Gross_output_sales_Real_USD
SCROLLS	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Value_added_output_Real_USD
SCROLLS	Index_of_industrial_production
"""

topline_rows = [
    tuple(line.split("\t", 1))
    for line in topline_raw.strip().split("\n")
]

topline_schema = StructType([
    StructField("Product_Category", StringType(), False),
    StructField("Indicator", StringType(), False)
])

topline_drivers = spark.createDataFrame(topline_rows, topline_schema)


# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

middle_raw = """
APAC	ALU	Leisure_Hospitality_Buildings
APAC	ALU	Stores
APAC	ALU	Data_Center
APAC	ALU	Electricity_installed_capacity
APAC	ALU	Real_GDP_total_2015_prices
APAC	ALU	Greenhouse_gas_emissions
APAC	ALU	Meat_production_total
APAC	ALU	General_purpose_machinery_NACE_rv2_28_1_28_2_Investment_Real_USD
APAC	ALU	Mechanical_engineering_NACE_rv2_28_Value_added_output_Real_USD
APAC	ALU	Real_GVA_in_construction
APAC	ALU	Food_beverages_NACE_rv2_10_11_Investment_Real_USD
APAC	ALU	Gas_steam_cooling_ice_manufacture_distribution_NACE_rv2_35_2_to_35_3_Value_added_output_Real_USD
APAC	ALU	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Gross_output_sales_Real_USD
APAC	ALU	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Value_added_output_Real_USD
APAC	ALU	Index_of_industrial_production
APAC	AVP_CDU	CO2_emissions
APAC	AVP_CDU	Leisure_Hospitality_Buildings
APAC	AVP_CDU	Stores
APAC	AVP_CDU	Food_Processing_Plants
APAC	AVP_CDU	Cold_Storage_Plants
APAC	AVP_CDU	General_purpose_machinery_NACE_rv2_28_1_28_2_Investment_Real_USD
APAC	AVP_CDU	Mechanical_engineering_NACE_rv2_28_Value_added_output_Real_USD
APAC	AVP_CDU	Real_GVA_in_construction
APAC	AVP_CDU	Food_beverages_NACE_rv2_10_11_Investment_Real_USD
APAC	AVP_CDU	Gas_steam_cooling_ice_manufacture_distribution_NACE_rv2_35_2_to_35_3_Value_added_output_Real_USD
APAC	AVP_CDU	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Gross_output_sales_Real_USD
APAC	AVP_CDU	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Value_added_output_Real_USD
APAC	AVP_CDU	Index_of_industrial_production
APAC	HEXPV	Data_Center
APAC	HEXPV	Leisure_Hospitality_Buildings
APAC	HEXPV	Stores
APAC	HEXPV	Manufacturing_NACE_rv2_10_to_33_Investment_Real_USD
APAC	HEXPV	Food_Processing_Plants
APAC	HEXPV	Cold_Storage_Plants
APAC	HEXPV	Electricity_gas_air_conditioning_NACE_rv2_35_Gross_output_sales_Real_USD
APAC	HEXPV	General_purpose_machinery_NACE_rv2_28_1_28_2_Investment_Real_USD
APAC	HEXPV	Mechanical_engineering_NACE_rv2_28_Value_added_output_Real_USD
APAC	HEXPV	Real_GVA_in_construction
APAC	HEXPV	Food_beverages_NACE_rv2_10_11_Investment_Real_USD
APAC	HEXPV	Gas_steam_cooling_ice_manufacture_distribution_NACE_rv2_35_2_to_35_3_Value_added_output_Real_USD
APAC	HEXPV	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Gross_output_sales_Real_USD
APAC	HEXPV	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Value_added_output_Real_USD
APAC	HEXPV	Index_of_industrial_production
APAC	PISTON	Whole_Economy_Price_of_energy_for_industr
APAC	PISTON	External_trade_Total_trade
APAC	PISTON	Food_Processing_Plants
APAC	PISTON	Cold_Storage_Plants
APAC	PISTON	General_purpose_machinery_NACE_rv2_28_1_28_2_Investment_Real_USD
APAC	PISTON	Mechanical_engineering_NACE_rv2_28_Value_added_output_Real_USD
APAC	PISTON	Real_GVA_in_construction
APAC	PISTON	Food_beverages_NACE_rv2_10_11_Investment_Real_USD
APAC	PISTON	Gas_steam_cooling_ice_manufacture_distribution_NACE_rv2_35_2_to_35_3_Value_added_output_Real_USD
APAC	PISTON	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Gross_output_sales_Real_USD
APAC	PISTON	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Value_added_output_Real_USD
APAC	PISTON	Index_of_industrial_production
APAC	SCREWS	Data_Center
APAC	SCREWS	Food_Processing_Plants
APAC	SCREWS	Cold_Storage_Plants
APAC	SCREWS	Greenhouse_gas_emissions
APAC	SCREWS	Gas_steam_cooling_ice_manufacture_distribution_NACE_rv2_35_2_to_35_3_Investment_Real_USD
APAC	SCREWS	CO2_emissions
APAC	SCREWS	Food_production_index
APAC	SCREWS	Meat_production_total
APAC	SCREWS	General_purpose_machinery_NACE_rv2_28_1_28_2_Investment_Real_USD
APAC	SCREWS	Mechanical_engineering_NACE_rv2_28_Value_added_output_Real_USD
APAC	SCREWS	Real_GVA_in_construction
APAC	SCREWS	Food_beverages_NACE_rv2_10_11_Investment_Real_USD
APAC	SCREWS	Gas_steam_cooling_ice_manufacture_distribution_NACE_rv2_35_2_to_35_3_Value_added_output_Real_USD
APAC	SCREWS	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Gross_output_sales_Real_USD
APAC	SCREWS	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Value_added_output_Real_USD
APAC	SCREWS	Index_of_industrial_production
APAC	SCROLLS	Food_Processing_Plants
APAC	SCROLLS	Cold_Storage_Plants
APAC	SCROLLS	HVAC
APAC	SCROLLS	Leisure_Hospitality_Buildings
APAC	SCROLLS	Stores
APAC	SCROLLS	General_purpose_machinery_NACE_rv2_28_1_28_2_Investment_Real_USD
APAC	SCROLLS	Mechanical_engineering_NACE_rv2_28_Value_added_output_Real_USD
APAC	SCROLLS	Real_GVA_in_construction
APAC	SCROLLS	Food_beverages_NACE_rv2_10_11_Investment_Real_USD
APAC	SCROLLS	Gas_steam_cooling_ice_manufacture_distribution_NACE_rv2_35_2_to_35_3_Value_added_output_Real_USD
APAC	SCROLLS	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Gross_output_sales_Real_USD
APAC	SCROLLS	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Value_added_output_Real_USD
APAC	SCROLLS	Index_of_industrial_production
APAC	SCROLLS	Data_Center
APAC	SCROLLS	Building_stock_by_type_Non_residential_number_of_buildings
China	ALU	Leisure_Hospitality_Buildings
China	ALU	Stores
China	ALU	International_investment_position_Net_total
China	ALU	General_purpose_machinery_NACE_rv2_28_1_28_2_Investment_Real_USD
China	ALU	Mechanical_engineering_NACE_rv2_28_Value_added_output_Real_USD
China	ALU	Real_GVA_in_construction
China	ALU	Food_beverages_NACE_rv2_10_11_Investment_Real_USD
China	ALU	Gas_steam_cooling_ice_manufacture_distribution_NACE_rv2_35_2_to_35_3_Value_added_output_Real_USD
China	ALU	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Gross_output_sales_Real_USD
China	ALU	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Value_added_output_Real_USD
China	ALU	Index_of_industrial_production
China	AVP_CDU	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Investment_Real_USD
China	AVP_CDU	Leisure_Hospitality_Buildings
China	AVP_CDU	Stores
China	AVP_CDU	General_purpose_machinery_NACE_rv2_28_1_28_2_Investment_Real_USD
China	AVP_CDU	Mechanical_engineering_NACE_rv2_28_Value_added_output_Real_USD
China	AVP_CDU	Real_GVA_in_construction
China	AVP_CDU	Food_beverages_NACE_rv2_10_11_Investment_Real_USD
China	AVP_CDU	Gas_steam_cooling_ice_manufacture_distribution_NACE_rv2_35_2_to_35_3_Value_added_output_Real_USD
China	AVP_CDU	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Gross_output_sales_Real_USD
China	AVP_CDU	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Value_added_output_Real_USD
China	AVP_CDU	Index_of_industrial_production
China	HEXPV	CO2_emissions
China	HEXPV	General_purpose_machinery_NACE_rv2_28_1_28_2_Investment_Real_USD
China	HEXPV	Mechanical_engineering_NACE_rv2_28_Value_added_output_Real_USD
China	HEXPV	Real_GVA_in_construction
China	HEXPV	Food_beverages_NACE_rv2_10_11_Investment_Real_USD
China	HEXPV	Gas_steam_cooling_ice_manufacture_distribution_NACE_rv2_35_2_to_35_3_Value_added_output_Real_USD
China	HEXPV	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Gross_output_sales_Real_USD
China	HEXPV	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Value_added_output_Real_USD
China	HEXPV	Index_of_industrial_production
China	MAERSK_COMPRESSOR	Electricity_installed_capacity
China	MAERSK_COMPRESSOR	Special_purpose_machinery_NACE_rv2_28_3_28_4_28_9_Investment_Real_USD
China	MAERSK_COMPRESSOR	Industrial_production_including_construction_excluding_utilities_NACE_rv2_05_to_33_41_to_43_Carbon_Emissions
China	MAERSK_COMPRESSOR	Mechanical_engineering_NACE_rv2_28_Investment_Real_USD
China	MAERSK_COMPRESSOR	General_purpose_machinery_NACE_rv2_28_1_28_2_Investment_Real_USD
China	MAERSK_COMPRESSOR	Mechanical_engineering_NACE_rv2_28_Value_added_output_Real_USD
China	MAERSK_COMPRESSOR	Real_GVA_in_construction
China	MAERSK_COMPRESSOR	Food_beverages_NACE_rv2_10_11_Investment_Real_USD
China	MAERSK_COMPRESSOR	Gas_steam_cooling_ice_manufacture_distribution_NACE_rv2_35_2_to_35_3_Value_added_output_Real_USD
China	MAERSK_COMPRESSOR	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Gross_output_sales_Real_USD
China	MAERSK_COMPRESSOR	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Value_added_output_Real_USD
China	MAERSK_COMPRESSOR	Index_of_industrial_production
China	PISTON	Industrial_production_excluding_Construction_NACE_rv2_05_to_39_Value_added_output_Real_USD
China	PISTON	Manufacturing_NACE_rv2_10_to_33_Value_added_output_Real_USD
China	PISTON	Whole_Economy_Gross_Domestic_Product_Real_USD
China	PISTON	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Value_added_output_Real_USD
China	PISTON	Wood_wood_products_Pulp_paper_Rubber_plastic_Non_metallic_minerals_NACE_rv2_16_to_17_22_to_23_Industrial_and_building_materials_chartbook_consistent_NACE_rv2_16_to_17_22_to_23
China	PISTON	Leisure_Hospitality_Buildings
China	PISTON	Stores
China	PISTON	Data_Center
China	PISTON	Manufacturing_NACE_rv2_10_to_33_Electricity_demand
China	PISTON	General_purpose_machinery_NACE_rv2_28_1_28_2_Investment_Real_USD
China	PISTON	Mechanical_engineering_NACE_rv2_28_Value_added_output_Real_USD
China	PISTON	Real_GVA_in_construction
China	PISTON	Food_beverages_NACE_rv2_10_11_Investment_Real_USD
China	PISTON	Gas_steam_cooling_ice_manufacture_distribution_NACE_rv2_35_2_to_35_3_Value_added_output_Real_USD
China	PISTON	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Gross_output_sales_Real_USD
China	PISTON	Index_of_industrial_production
China	SCREWS	Pharmaceuticals_NACE_rv2_21_Value_added_output_Real_USD
China	SCREWS	Index_of_industrial_production
China	SCREWS	HVAC
China	SCREWS	Data_Center
China	SCREWS	Meat_production_total
China	SCREWS	International_investment_position_Net_total
China	SCREWS	Special_purpose_machinery_NACE_rv2_28_3_28_4_28_9_Investment_Real_USD
China	SCREWS	CO2_emissions
China	SCREWS	General_purpose_machinery_NACE_rv2_28_1_28_2_Investment_Real_USD
China	SCREWS	Mechanical_engineering_NACE_rv2_28_Value_added_output_Real_USD
China	SCREWS	Real_GVA_in_construction
China	SCREWS	Food_beverages_NACE_rv2_10_11_Investment_Real_USD
China	SCREWS	Gas_steam_cooling_ice_manufacture_distribution_NACE_rv2_35_2_to_35_3_Value_added_output_Real_USD
China	SCREWS	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Gross_output_sales_Real_USD
China	SCREWS	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Value_added_output_Real_USD
China	SCROLLS	Data_Center
China	SCROLLS	Leisure_Hospitality_Buildings
China	SCROLLS	Stores
China	SCROLLS	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Gross_output_sales_Real_USD
China	SCROLLS	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Value_added_output_Real_USD
China	SCROLLS	General_purpose_machinery_NACE_rv2_28_1_28_2_Investment_Real_USD
China	SCROLLS	Mechanical_engineering_NACE_rv2_28_Value_added_output_Real_USD
China	SCROLLS	Real_GVA_in_construction
China	SCROLLS	Food_beverages_NACE_rv2_10_11_Investment_Real_USD
China	SCROLLS	Gas_steam_cooling_ice_manufacture_distribution_NACE_rv2_35_2_to_35_3_Value_added_output_Real_USD
China	SCROLLS	Index_of_industrial_production
China	SCROLLS	Building_stock_by_type_Non_residential_number_of_buildings
EMEA	ALU	General_purpose_machinery_NACE_rv2_28_1_28_2_Investment_Real_USD
EMEA	ALU	Mechanical_engineering_NACE_rv2_28_Value_added_output_Real_USD
EMEA	ALU	Real_GVA_in_construction
EMEA	ALU	Food_beverages_NACE_rv2_10_11_Investment_Real_USD
EMEA	ALU	Gas_steam_cooling_ice_manufacture_distribution_NACE_rv2_35_2_to_35_3_Value_added_output_Real_USD
EMEA	ALU	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Gross_output_sales_Real_USD
EMEA	ALU	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Value_added_output_Real_USD
EMEA	ALU	Index_of_industrial_production
EMEA	AVP_CDU	Building_stock_by_type_Non_residential_number_of_buildings
EMEA	AVP_CDU	Leisure_Hospitality_Buildings
EMEA	AVP_CDU	Stores
EMEA	AVP_CDU	Food_Processing_Plants
EMEA	AVP_CDU	Cold_Storage_Plants
EMEA	AVP_CDU	General_purpose_machinery_NACE_rv2_28_1_28_2_Investment_Real_USD
EMEA	AVP_CDU	Mechanical_engineering_NACE_rv2_28_Value_added_output_Real_USD
EMEA	AVP_CDU	Real_GVA_in_construction
EMEA	AVP_CDU	Food_beverages_NACE_rv2_10_11_Investment_Real_USD
EMEA	AVP_CDU	Gas_steam_cooling_ice_manufacture_distribution_NACE_rv2_35_2_to_35_3_Value_added_output_Real_USD
EMEA	AVP_CDU	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Gross_output_sales_Real_USD
EMEA	AVP_CDU	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Value_added_output_Real_USD
EMEA	AVP_CDU	Index_of_industrial_production
EMEA	HEXPV	Leisure_Hospitality_Buildings
EMEA	HEXPV	Stores
EMEA	HEXPV	Food_Processing_Plants
EMEA	HEXPV	Cold_Storage_Plants
EMEA	HEXPV	Data_Center
EMEA	HEXPV	HVAC
EMEA	HEXPV	International_investment_position_Net_total
EMEA	HEXPV	General_purpose_machinery_NACE_rv2_28_1_28_2_Investment_Real_USD
EMEA	HEXPV	Mechanical_engineering_NACE_rv2_28_Value_added_output_Real_USD
EMEA	HEXPV	Real_GVA_in_construction
EMEA	HEXPV	Food_beverages_NACE_rv2_10_11_Investment_Real_USD
EMEA	HEXPV	Gas_steam_cooling_ice_manufacture_distribution_NACE_rv2_35_2_to_35_3_Value_added_output_Real_USD
EMEA	HEXPV	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Gross_output_sales_Real_USD
EMEA	HEXPV	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Value_added_output_Real_USD
EMEA	HEXPV	Index_of_industrial_production
EMEA	MAERSK_COMPRESSOR	CO2_emissions
EMEA	MAERSK_COMPRESSOR	General_purpose_machinery_NACE_rv2_28_1_28_2_Investment_Real_USD
EMEA	MAERSK_COMPRESSOR	Mechanical_engineering_NACE_rv2_28_Value_added_output_Real_USD
EMEA	MAERSK_COMPRESSOR	Real_GVA_in_construction
EMEA	MAERSK_COMPRESSOR	Food_beverages_NACE_rv2_10_11_Investment_Real_USD
EMEA	MAERSK_COMPRESSOR	Gas_steam_cooling_ice_manufacture_distribution_NACE_rv2_35_2_to_35_3_Value_added_output_Real_USD
EMEA	MAERSK_COMPRESSOR	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Gross_output_sales_Real_USD
EMEA	MAERSK_COMPRESSOR	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Value_added_output_Real_USD
EMEA	MAERSK_COMPRESSOR	Index_of_industrial_production
EMEA	PISTON	Leisure_Hospitality_Buildings
EMEA	PISTON	Stores
EMEA	PISTON	Data_Center
EMEA	PISTON	Food_Processing_Plants
EMEA	PISTON	Cold_Storage_Plants
EMEA	PISTON	Building_stock_by_type_Non_residential_number_of_buildings
EMEA	PISTON	HVAC
EMEA	PISTON	General_purpose_machinery_NACE_rv2_28_1_28_2_Investment_Real_USD
EMEA	PISTON	Mechanical_engineering_NACE_rv2_28_Value_added_output_Real_USD
EMEA	PISTON	Real_GVA_in_construction
EMEA	PISTON	Food_beverages_NACE_rv2_10_11_Investment_Real_USD
EMEA	PISTON	Gas_steam_cooling_ice_manufacture_distribution_NACE_rv2_35_2_to_35_3_Value_added_output_Real_USD
EMEA	PISTON	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Gross_output_sales_Real_USD
EMEA	PISTON	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Value_added_output_Real_USD
EMEA	PISTON	Index_of_industrial_production
EMEA	SCREWS	Industrial_production_including_construction_excluding_utilities_NACE_rv2_05_to_33_41_to_43_Carbon_Emissions
EMEA	SCREWS	Real_GVA_in_manufacturing
EMEA	SCREWS	Gas_steam_cooling_ice_manufacture_distribution_NACE_rv2_35_2_to_35_3_Investment_Real_USD
EMEA	SCREWS	Manufacturing_NACE_rv2_10_to_33_Investment_Real_USD
EMEA	SCREWS	Data_Center
EMEA	SCREWS	Food_Processing_Plants
EMEA	SCREWS	Cold_Storage_Plants
EMEA	SCREWS	IT_Programming_consultancy_information_services_NACE_rv2_62_to_63_Investment_Real_USD
EMEA	SCREWS	General_purpose_machinery_NACE_rv2_28_1_28_2_Investment_Real_USD
EMEA	SCREWS	Mechanical_engineering_NACE_rv2_28_Value_added_output_Real_USD
EMEA	SCREWS	Real_GVA_in_construction
EMEA	SCREWS	Food_beverages_NACE_rv2_10_11_Investment_Real_USD
EMEA	SCREWS	Gas_steam_cooling_ice_manufacture_distribution_NACE_rv2_35_2_to_35_3_Value_added_output_Real_USD
EMEA	SCREWS	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Gross_output_sales_Real_USD
EMEA	SCREWS	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Value_added_output_Real_USD
EMEA	SCREWS	Index_of_industrial_production
EMEA	SCROLLS	Mechanical_engineering_NACE_rv2_28_Gross_output_sales_Real_USD
EMEA	SCROLLS	Leisure_Hospitality_Buildings
EMEA	SCROLLS	Stores
EMEA	SCROLLS	Data_Center
EMEA	SCROLLS	Building_stock_by_type_Non_residential_number_of_buildings
EMEA	SCROLLS	Special_purpose_machinery_NACE_rv2_28_3_28_4_28_9_Gross_output_sales_Real_USD
EMEA	SCROLLS	General_purpose_machinery_NACE_rv2_28_1_28_2_Investment_Real_USD
EMEA	SCROLLS	Mechanical_engineering_NACE_rv2_28_Value_added_output_Real_USD
EMEA	SCROLLS	Real_GVA_in_construction
EMEA	SCROLLS	Food_beverages_NACE_rv2_10_11_Investment_Real_USD
EMEA	SCROLLS	Gas_steam_cooling_ice_manufacture_distribution_NACE_rv2_35_2_to_35_3_Value_added_output_Real_USD
EMEA	SCROLLS	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Gross_output_sales_Real_USD
EMEA	SCROLLS	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Value_added_output_Real_USD
EMEA	SCROLLS	Index_of_industrial_production
N.America	ALU	General_purpose_machinery_NACE_rv2_28_1_28_2_Investment_Real_USD
N.America	ALU	Mechanical_engineering_NACE_rv2_28_Value_added_output_Real_USD
N.America	ALU	Real_GVA_in_construction
N.America	ALU	Food_beverages_NACE_rv2_10_11_Investment_Real_USD
N.America	ALU	Gas_steam_cooling_ice_manufacture_distribution_NACE_rv2_35_2_to_35_3_Value_added_output_Real_USD
N.America	ALU	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Gross_output_sales_Real_USD
N.America	ALU	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Value_added_output_Real_USD
N.America	ALU	Index_of_industrial_production
N.America	AVP_CDU	Food_Processing_Plants
N.America	AVP_CDU	Cold_Storage_Plants
N.America	AVP_CDU	International_investment_position_Net_total
N.America	AVP_CDU	Leisure_Hospitality_Buildings
N.America	AVP_CDU	Stores
N.America	AVP_CDU	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Value_added_output_Real_USD
N.America	AVP_CDU	General_purpose_machinery_NACE_rv2_28_1_28_2_Investment_Real_USD
N.America	AVP_CDU	Mechanical_engineering_NACE_rv2_28_Value_added_output_Real_USD
N.America	AVP_CDU	Real_GVA_in_construction
N.America	AVP_CDU	Food_beverages_NACE_rv2_10_11_Investment_Real_USD
N.America	AVP_CDU	Gas_steam_cooling_ice_manufacture_distribution_NACE_rv2_35_2_to_35_3_Value_added_output_Real_USD
N.America	AVP_CDU	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Gross_output_sales_Real_USD
N.America	AVP_CDU	Index_of_industrial_production
N.America	HEXPV	Leisure_Hospitality_Buildings
N.America	HEXPV	Stores
N.America	HEXPV	Data_Center
N.America	HEXPV	Gas_steam_cooling_ice_manufacture_distribution_NACE_rv2_35_2_to_35_3_Gross_output_sales_Real_USD
N.America	HEXPV	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Gross_output_sales_Real_USD
N.America	HEXPV	Index_of_industrial_production
N.America	HEXPV	Food_Processing_Plants
N.America	HEXPV	Cold_Storage_Plants
N.America	HEXPV	General_purpose_machinery_NACE_rv2_28_1_28_2_Investment_Real_USD
N.America	HEXPV	Mechanical_engineering_NACE_rv2_28_Value_added_output_Real_USD
N.America	HEXPV	Real_GVA_in_construction
N.America	HEXPV	Food_beverages_NACE_rv2_10_11_Investment_Real_USD
N.America	HEXPV	Gas_steam_cooling_ice_manufacture_distribution_NACE_rv2_35_2_to_35_3_Value_added_output_Real_USD
N.America	HEXPV	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Value_added_output_Real_USD
N.America	MAERSK_ELECTRONICS	International_investment_position_Net_total
N.America	MAERSK_ELECTRONICS	General_purpose_machinery_NACE_rv2_28_1_28_2_Investment_Real_USD
N.America	MAERSK_ELECTRONICS	Mechanical_engineering_NACE_rv2_28_Value_added_output_Real_USD
N.America	MAERSK_ELECTRONICS	Real_GVA_in_construction
N.America	MAERSK_ELECTRONICS	Food_beverages_NACE_rv2_10_11_Investment_Real_USD
N.America	MAERSK_ELECTRONICS	Gas_steam_cooling_ice_manufacture_distribution_NACE_rv2_35_2_to_35_3_Value_added_output_Real_USD
N.America	MAERSK_ELECTRONICS	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Gross_output_sales_Real_USD
N.America	MAERSK_ELECTRONICS	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Value_added_output_Real_USD
N.America	MAERSK_ELECTRONICS	Index_of_industrial_production
N.America	PISTON	Leisure_Hospitality_Buildings
N.America	PISTON	Stores
N.America	PISTON	Whole_Economy_Price_of_energy_for_industr
N.America	PISTON	IT_Programming_consultancy_information_services_NACE_rv2_62_to_63_Gross_output_sales_Real_USD
N.America	PISTON	Index_of_industrial_production
N.America	PISTON	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Value_added_output_Real_USD
N.America	PISTON	IT_Programming_consultancy_information_services_NACE_rv2_62_to_63_Value_added_output_Real_USD
N.America	PISTON	International_investment_position_Net_total
N.America	PISTON	Food_Processing_Plants
N.America	PISTON	Cold_Storage_Plants
N.America	PISTON	General_purpose_machinery_NACE_rv2_28_1_28_2_Investment_Real_USD
N.America	PISTON	Mechanical_engineering_NACE_rv2_28_Value_added_output_Real_USD
N.America	PISTON	Real_GVA_in_construction
N.America	PISTON	Food_beverages_NACE_rv2_10_11_Investment_Real_USD
N.America	PISTON	Gas_steam_cooling_ice_manufacture_distribution_NACE_rv2_35_2_to_35_3_Value_added_output_Real_USD
N.America	PISTON	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Gross_output_sales_Real_USD
N.America	SCREWS	Data_Center
N.America	SCREWS	Food_Processing_Plants
N.America	SCREWS	Cold_Storage_Plants
N.America	SCREWS	International_investment_position_Net_total
N.America	SCREWS	IT_Programming_consultancy_information_services_NACE_rv2_62_to_63_Value_added_output_Real_USD
N.America	SCREWS	Greenhouse_gas_emissions
N.America	SCREWS	HVAC
N.America	SCREWS	IT_Programming_consultancy_information_services_NACE_rv2_62_to_63_Gross_output_sales_Real_USD
N.America	SCREWS	General_purpose_machinery_NACE_rv2_28_1_28_2_Investment_Real_USD
N.America	SCREWS	Mechanical_engineering_NACE_rv2_28_Value_added_output_Real_USD
N.America	SCREWS	Real_GVA_in_construction
N.America	SCREWS	Food_beverages_NACE_rv2_10_11_Investment_Real_USD
N.America	SCREWS	Gas_steam_cooling_ice_manufacture_distribution_NACE_rv2_35_2_to_35_3_Value_added_output_Real_USD
N.America	SCREWS	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Gross_output_sales_Real_USD
N.America	SCREWS	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Value_added_output_Real_USD
N.America	SCREWS	Index_of_industrial_production
N.America	SCROLLS	Greenhouse_gas_emissions
N.America	SCROLLS	International_investment_position_Net_total
N.America	SCROLLS	Construction_Sector
N.America	SCROLLS	Data_Center
N.America	SCROLLS	General_purpose_machinery_NACE_rv2_28_1_28_2_Investment_Real_USD
N.America	SCROLLS	Mechanical_engineering_NACE_rv2_28_Value_added_output_Real_USD
N.America	SCROLLS	Real_GVA_in_construction
N.America	SCROLLS	Food_beverages_NACE_rv2_10_11_Investment_Real_USD
N.America	SCROLLS	Gas_steam_cooling_ice_manufacture_distribution_NACE_rv2_35_2_to_35_3_Value_added_output_Real_USD
N.America	SCROLLS	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Gross_output_sales_Real_USD
N.America	SCROLLS	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Value_added_output_Real_USD
N.America	SCROLLS	Index_of_industrial_production
N.America	SCROLLS	Building_stock_by_type_Non_residential_number_of_buildings
S.America	ALU	International_investment_position_Net_total
S.America	ALU	Greenhouse_gas_emissions
S.America	ALU	General_purpose_machinery_NACE_rv2_28_1_28_2_Investment_Real_USD
S.America	ALU	Mechanical_engineering_NACE_rv2_28_Value_added_output_Real_USD
S.America	ALU	Real_GVA_in_construction
S.America	ALU	Food_beverages_NACE_rv2_10_11_Investment_Real_USD
S.America	ALU	Gas_steam_cooling_ice_manufacture_distribution_NACE_rv2_35_2_to_35_3_Value_added_output_Real_USD
S.America	ALU	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Gross_output_sales_Real_USD
S.America	ALU	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Value_added_output_Real_USD
S.America	ALU	Index_of_industrial_production
S.America	AVP_CDU	Leisure_Hospitality_Buildings
S.America	AVP_CDU	Stores
S.America	AVP_CDU	Industrial_production_excluding_Construction_NACE_rv2_05_to_39_Investment_Nominal_USD
S.America	AVP_CDU	Food_Processing_Plants
S.America	AVP_CDU	Cold_Storage_Plants
S.America	AVP_CDU	General_purpose_machinery_NACE_rv2_28_1_28_2_Investment_Real_USD
S.America	AVP_CDU	Mechanical_engineering_NACE_rv2_28_Value_added_output_Real_USD
S.America	AVP_CDU	Real_GVA_in_construction
S.America	AVP_CDU	Food_beverages_NACE_rv2_10_11_Investment_Real_USD
S.America	AVP_CDU	Gas_steam_cooling_ice_manufacture_distribution_NACE_rv2_35_2_to_35_3_Value_added_output_Real_USD
S.America	AVP_CDU	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Gross_output_sales_Real_USD
S.America	AVP_CDU	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Value_added_output_Real_USD
S.America	AVP_CDU	Index_of_industrial_production
S.America	HEXPV	Mechanical_engineering_NACE_rv2_28_Investment_Real_USD
S.America	HEXPV	Whole_Economy_Producer_Price_Index
S.America	HEXPV	Food_Processing_Plants
S.America	HEXPV	Cold_Storage_Plants
S.America	HEXPV	Whole_Economy_Price_of_energy_for_industr
S.America	HEXPV	Leisure_Hospitality_Buildings
S.America	HEXPV	Stores
S.America	HEXPV	Data_Center
S.America	HEXPV	General_purpose_machinery_NACE_rv2_28_1_28_2_Investment_Real_USD
S.America	HEXPV	Mechanical_engineering_NACE_rv2_28_Value_added_output_Real_USD
S.America	HEXPV	Real_GVA_in_construction
S.America	HEXPV	Food_beverages_NACE_rv2_10_11_Investment_Real_USD
S.America	HEXPV	Gas_steam_cooling_ice_manufacture_distribution_NACE_rv2_35_2_to_35_3_Value_added_output_Real_USD
S.America	HEXPV	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Gross_output_sales_Real_USD
S.America	HEXPV	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Value_added_output_Real_USD
S.America	HEXPV	Index_of_industrial_production
S.America	PISTON	IT_Programming_consultancy_information_services_NACE_rv2_62_to_63_Value_added_output_Real_USD
S.America	PISTON	Castings_NACE_rv2_24_5_Value_added_output_Real_USD
S.America	PISTON	General_purpose_machinery_NACE_rv2_28_1_28_2_Investment_Real_USD
S.America	PISTON	Mechanical_engineering_NACE_rv2_28_Value_added_output_Real_USD
S.America	PISTON	Real_GVA_in_construction
S.America	PISTON	Food_beverages_NACE_rv2_10_11_Investment_Real_USD
S.America	PISTON	Gas_steam_cooling_ice_manufacture_distribution_NACE_rv2_35_2_to_35_3_Value_added_output_Real_USD
S.America	PISTON	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Gross_output_sales_Real_USD
S.America	PISTON	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Value_added_output_Real_USD
S.America	PISTON	Index_of_industrial_production
S.America	SCREWS	Food_beverages_NACE_rv2_10_11_Gross_output_sales_Real_USD
S.America	SCREWS	Whole_Economy_Price_of_energy_for_industr
S.America	SCREWS	Greenhouse_gas_emissions
S.America	SCREWS	Whole_Economy_Producer_Price_Index
S.America	SCREWS	Meat_production_total
S.America	SCREWS	Data_Center
S.America	SCREWS	Food_Processing_Plants
S.America	SCREWS	Cold_Storage_Plants
S.America	SCREWS	General_purpose_machinery_NACE_rv2_28_1_28_2_Investment_Real_USD
S.America	SCREWS	Mechanical_engineering_NACE_rv2_28_Value_added_output_Real_USD
S.America	SCREWS	Real_GVA_in_construction
S.America	SCREWS	Food_beverages_NACE_rv2_10_11_Investment_Real_USD
S.America	SCREWS	Gas_steam_cooling_ice_manufacture_distribution_NACE_rv2_35_2_to_35_3_Value_added_output_Real_USD
S.America	SCREWS	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Gross_output_sales_Real_USD
S.America	SCREWS	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Value_added_output_Real_USD
S.America	SCREWS	Index_of_industrial_production
S.America	SCROLLS	International_investment_position_Net_total
S.America	SCROLLS	Greenhouse_gas_emissions
S.America	SCROLLS	Whole_Economy_Price_of_energy_for_industr
S.America	SCROLLS	Data_Center
S.America	SCROLLS	General_purpose_machinery_NACE_rv2_28_1_28_2_Investment_Real_USD
S.America	SCROLLS	Mechanical_engineering_NACE_rv2_28_Value_added_output_Real_USD
S.America	SCROLLS	Real_GVA_in_construction
S.America	SCROLLS	Food_beverages_NACE_rv2_10_11_Investment_Real_USD
S.America	SCROLLS	Gas_steam_cooling_ice_manufacture_distribution_NACE_rv2_35_2_to_35_3_Value_added_output_Real_USD
S.America	SCROLLS	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Gross_output_sales_Real_USD
S.America	SCROLLS	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Gross_output_sales_Real_USD
S.America	SCROLLS	Construction_Non_residential_Building_NACE_rv2_41_2_1_part_41_1_part_43_Value_added_output_Real_USD
S.America	SCROLLS	Index_of_industrial_production
"""



middle_rows = [
    tuple(line.split("\t", 2))
    for line in middle_raw.strip().split("\n")
]

middle_schema = StructType([
    StructField("Region", StringType(), False),
    StructField("Product_Category", StringType(), False),
    StructField("Indicator", StringType(), False)
])

middle_drivers = spark.createDataFrame(middle_rows, middle_schema)


# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

## dataframes with selected drivers
topline_drivers
middle_drivers

## dataframes with the recommended lags
df

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

if Topline:
    drivers = topline_drivers
else:
    drivers = middle_drivers


# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

print(drivers.columns)
print(df.columns)


num_selected_drivers = drivers.count()
print(f"number of selected driver records: {num_selected_drivers}")

joined_df = drivers.join(
    df.filter(col('rec_lag')==1).select(*partition_cols,'Lag','rec_lag','max_corr'), 
    partition_cols, 
    'inner'
)

display(joined_df.select(*partition_cols).distinct().orderBy(*partition_cols))
print(joined_df.count())

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

## converting to pandas dataframe for Lakehouse Files writing
joined_pd = joined_df.toPandas()

## Writing to csv
joined_pd.to_csv(final_features_path)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************


# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }
